UPDATE PETSALE SET QUANTITY = 10 WHERE ID = 1;
UPDATE PETSALE SET QUANTITY = 12 WHERE ID = 2;
UPDATE PETSALE SET QUANTITY = 24 WHERE ID = 3;
UPDATE PETSALE SET QUANTITY = 64 WHERE ID = 4;
UPDATE PETSALE SET QUANTITY = 124 WHERE ID = 5;

SELECT *
FROM PETSALE;